-- ============================================================
-- V8: 为所有数据表、字段补充中文注释
-- ============================================================

-- ====== 管理员系统 ======
ALTER TABLE admin_user COMMENT '管理员账号';
ALTER TABLE admin_user MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE admin_user MODIFY COLUMN username VARCHAR(64) NOT NULL COMMENT '用户名';
ALTER TABLE admin_user MODIFY COLUMN password_hash VARCHAR(256) NOT NULL COMMENT '密码哈希(BCrypt)';
ALTER TABLE admin_user MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状���: ACTIVE/LOCKED/DISABLED';
ALTER TABLE admin_user MODIFY COLUMN failed_login_attempts INT NOT NULL DEFAULT 0 COMMENT '连续登录失败次数';
ALTER TABLE admin_user MODIFY COLUMN locked_until DATETIME NULL COMMENT '锁定截止时间';
ALTER TABLE admin_user MODIFY COLUMN last_login_at DATETIME NULL COMMENT '最后登录时间';
ALTER TABLE admin_user MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE admin_user MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE admin_role COMMENT '管理员角色';
ALTER TABLE admin_role MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE admin_role MODIFY COLUMN role_code VARCHAR(64) NOT NULL COMMENT '角色编码: ADMIN/OPERATOR';
ALTER TABLE admin_role MODIFY COLUMN role_name VARCHAR(128) NOT NULL COMMENT '角色名称';
ALTER TABLE admin_role MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态';
ALTER TABLE admin_role MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE admin_permission COMMENT '管理员权限';
ALTER TABLE admin_permission MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE admin_permission MODIFY COLUMN permission_code VARCHAR(128) NOT NULL COMMENT '权限编码';
ALTER TABLE admin_permission MODIFY COLUMN permission_name VARCHAR(256) NOT NULL COMMENT '权限名称';
ALTER TABLE admin_permission MODIFY COLUMN resource_type VARCHAR(32) NOT NULL COMMENT '资源类型: MENU/BUTTON/API';
ALTER TABLE admin_permission MODIFY COLUMN path VARCHAR(256) NULL COMMENT '资源路径';
ALTER TABLE admin_permission MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE admin_user_role COMMENT '管理员-角色关联';
ALTER TABLE admin_user_role MODIFY COLUMN admin_user_id BIGINT NOT NULL COMMENT '管理员ID';
ALTER TABLE admin_user_role MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色ID';

ALTER TABLE admin_role_permission COMMENT '角色-权限关联';
ALTER TABLE admin_role_permission MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色ID';
ALTER TABLE admin_role_permission MODIFY COLUMN permission_id BIGINT NOT NULL COMMENT '权限ID';

ALTER TABLE admin_operation_log COMMENT '管理员操作日志';
ALTER TABLE admin_operation_log MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE admin_operation_log MODIFY COLUMN admin_user_id BIGINT NULL COMMENT '管理员ID';
ALTER TABLE admin_operation_log MODIFY COLUMN module VARCHAR(64) NOT NULL COMMENT '操作模块';
ALTER TABLE admin_operation_log MODIFY COLUMN operation VARCHAR(64) NOT NULL COMMENT '操作类型: CREATE/UPDATE/DELETE';
ALTER TABLE admin_operation_log MODIFY COLUMN business_id VARCHAR(128) NULL COMMENT '业务ID';
ALTER TABLE admin_operation_log MODIFY COLUMN before_json TEXT NULL COMMENT '操作前数据';
ALTER TABLE admin_operation_log MODIFY COLUMN after_json TEXT NULL COMMENT '操作后数据';
ALTER TABLE admin_operation_log MODIFY COLUMN result VARCHAR(32) NOT NULL COMMENT '结果: SUCCESS/FAILURE';
ALTER TABLE admin_operation_log MODIFY COLUMN request_id VARCHAR(64) NULL COMMENT '请求追踪ID';
ALTER TABLE admin_operation_log MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ====== APP版本管理 ======
ALTER TABLE app_version COMMENT 'APP版本发布记录';
ALTER TABLE app_version MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE app_version MODIFY COLUMN version_name VARCHAR(32) NOT NULL COMMENT '版本名: 0.9.202607261118';
ALTER TABLE app_version MODIFY COLUMN version_code INT NOT NULL COMMENT '版本号: 7261118';
ALTER TABLE app_version MODIFY COLUMN download_url VARCHAR(512) NULL COMMENT 'APK下载地址';
ALTER TABLE app_version MODIFY COLUMN release_notes TEXT NULL COMMENT '更新说明';
ALTER TABLE app_version MODIFY COLUMN force_update TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否强制更新';
ALTER TABLE app_version MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE/INACTIVE';
ALTER TABLE app_version MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE app_version MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ====== 配置发布 ======
ALTER TABLE config_release COMMENT '配置发布记录';
ALTER TABLE config_release MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE config_release MODIFY COLUMN release_no VARCHAR(64) NOT NULL COMMENT '发布编号';
ALTER TABLE config_release MODIFY COLUMN release_type VARCHAR(32) NOT NULL COMMENT '发布类型: ALL/GRAY';
ALTER TABLE config_release MODIFY COLUMN config_version VARCHAR(64) NOT NULL COMMENT '配置版本号';
ALTER TABLE config_release MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态: DRAFT/PUBLISHED/ARCHIVED';
ALTER TABLE config_release MODIFY COLUMN gray_percentage INT NULL DEFAULT 0 COMMENT '灰度百分比';
ALTER TABLE config_release MODIFY COLUMN description VARCHAR(512) NULL COMMENT '发布说明';
ALTER TABLE config_release MODIFY COLUMN published_at DATETIME NULL COMMENT '发布时间';
ALTER TABLE config_release MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人(管理员ID)';
ALTER TABLE config_release MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE config_release MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE config_release_item COMMENT '配置发布明细';
ALTER TABLE config_release_item MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE config_release_item MODIFY COLUMN release_id BIGINT NOT NULL COMMENT '发布ID';
ALTER TABLE config_release_item MODIFY COLUMN config_type VARCHAR(64) NOT NULL COMMENT '配置类型';
ALTER TABLE config_release_item MODIFY COLUMN business_id BIGINT NOT NULL COMMENT '业务ID';
ALTER TABLE config_release_item MODIFY COLUMN content_json TEXT NOT NULL COMMENT '配置内容JSON';
ALTER TABLE config_release_item MODIFY COLUMN content_hash VARCHAR(128) NULL COMMENT '内容哈希';
ALTER TABLE config_release_item MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ====== 权益管理 ======
ALTER TABLE entitlement COMMENT '权益定义';
ALTER TABLE entitlement MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE entitlement MODIFY COLUMN entitlement_name VARCHAR(128) NOT NULL COMMENT '权益名称';
ALTER TABLE entitlement MODIFY COLUMN entitlement_code VARCHAR(8) NOT NULL COMMENT '权益编码(8位)';
ALTER TABLE entitlement MODIFY COLUMN start_time DATETIME NULL COMMENT '开始时间';
ALTER TABLE entitlement MODIFY COLUMN end_time DATETIME NULL COMMENT '结束时间(空=永久)';
ALTER TABLE entitlement MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'ENABLED' COMMENT '状态: ENABLED/DISABLED';
ALTER TABLE entitlement MODIFY COLUMN owner_name VARCHAR(64) NULL COMMENT '持有人姓名';
ALTER TABLE entitlement MODIFY COLUMN owner_phone VARCHAR(32) NULL COMMENT '持有人手机号';
ALTER TABLE entitlement MODIFY COLUMN owner_profession VARCHAR(64) NULL COMMENT '持有人职业';
ALTER TABLE entitlement MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE entitlement MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE entitlement_code_batch COMMENT '权益码批次';
ALTER TABLE entitlement_code_batch MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE entitlement_code_batch MODIFY COLUMN batch_no VARCHAR(64) NOT NULL COMMENT '批次编号';
ALTER TABLE entitlement_code_batch MODIFY COLUMN product_id BIGINT NOT NULL COMMENT '产品ID';
ALTER TABLE entitlement_code_batch MODIFY COLUMN channel_code VARCHAR(64) NULL COMMENT '渠道编码';
ALTER TABLE entitlement_code_batch MODIFY COLUMN quantity INT NOT NULL DEFAULT 0 COMMENT '计划数量';
ALTER TABLE entitlement_code_batch MODIFY COLUMN generated_count INT NOT NULL DEFAULT 0 COMMENT '已生成数量';
ALTER TABLE entitlement_code_batch MODIFY COLUMN activated_count INT NOT NULL DEFAULT 0 COMMENT '已激活数量';
ALTER TABLE entitlement_code_batch MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'CREATED' COMMENT '状态: CREATED/GENERATING/COMPLETED';
ALTER TABLE entitlement_code_batch MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE entitlement_code_batch MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE entitlement_code COMMENT '权益码';
ALTER TABLE entitlement_code MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE entitlement_code MODIFY COLUMN batch_id BIGINT NOT NULL COMMENT '批次ID';
ALTER TABLE entitlement_code MODIFY COLUMN code_hash VARCHAR(128) NOT NULL COMMENT '权益码哈希(SHA256)';
ALTER TABLE entitlement_code MODIFY COLUMN code_masked VARCHAR(32) NULL COMMENT '权益码掩码(显示用)';
ALTER TABLE entitlement_code MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'UNUSED' COMMENT '状态: UNUSED/ACTIVATED/EXPIRED';
ALTER TABLE entitlement_code MODIFY COLUMN activated_user_id BIGINT NULL COMMENT '激活用户ID';
ALTER TABLE entitlement_code MODIFY COLUMN activated_at DATETIME NULL COMMENT '激活时间';
ALTER TABLE entitlement_code MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE entitlement_product COMMENT '权益产品';
ALTER TABLE entitlement_product MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE entitlement_product MODIFY COLUMN product_code VARCHAR(64) NOT NULL COMMENT '产品编码';
ALTER TABLE entitlement_product MODIFY COLUMN product_name VARCHAR(128) NOT NULL COMMENT '产品名称';
ALTER TABLE entitlement_product MODIFY COLUMN description VARCHAR(512) NULL COMMENT '产品描述';
ALTER TABLE entitlement_product MODIFY COLUMN validity_type VARCHAR(32) NOT NULL COMMENT '有效期类型: DAYS/RANGE/PERMANENT';
ALTER TABLE entitlement_product MODIFY COLUMN valid_days INT NULL COMMENT '有效天数';
ALTER TABLE entitlement_product MODIFY COLUMN valid_from DATETIME NULL COMMENT '有效期开始';
ALTER TABLE entitlement_product MODIFY COLUMN valid_until DATETIME NULL COMMENT '有效期截止';
ALTER TABLE entitlement_product MODIFY COLUMN daily_usage_limit INT NULL COMMENT '每日使用次数限制';
ALTER TABLE entitlement_product MODIFY COLUMN total_usage_limit INT NULL COMMENT '总使用次数限制';
ALTER TABLE entitlement_product MODIFY COLUMN device_limit INT NULL COMMENT '设备数量限制';
ALTER TABLE entitlement_product MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态: DRAFT/ACTIVE/INACTIVE';
ALTER TABLE entitlement_product MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE entitlement_product MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE entitlement_product_platform COMMENT '产品-平台关联';
ALTER TABLE entitlement_product_platform MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE entitlement_product_platform MODIFY COLUMN product_id BIGINT NOT NULL COMMENT '产品ID';
ALTER TABLE entitlement_product_platform MODIFY COLUMN platform_code VARCHAR(64) NOT NULL COMMENT '平台编码';
ALTER TABLE entitlement_product_platform MODIFY COLUMN scope_type VARCHAR(32) NOT NULL COMMENT '范围类型: INCLUDE/EXCLUDE';
ALTER TABLE entitlement_product_platform MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE entitlement_usage COMMENT '权益使用记录';
ALTER TABLE entitlement_usage MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE entitlement_usage MODIFY COLUMN user_entitlement_id BIGINT NOT NULL COMMENT '用户权益ID';
ALTER TABLE entitlement_usage MODIFY COLUMN platform_code VARCHAR(64) NOT NULL COMMENT '平台编码';
ALTER TABLE entitlement_usage MODIFY COLUMN content_key VARCHAR(256) NULL COMMENT '内容标识';
ALTER TABLE entitlement_usage MODIFY COLUMN usage_date DATE NOT NULL COMMENT '使用日期';
ALTER TABLE entitlement_usage MODIFY COLUMN usage_count INT NOT NULL DEFAULT 1 COMMENT '使用次数';
ALTER TABLE entitlement_usage MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ====== 播放路由（已删除模块，保留注释供参考） ======
ALTER TABLE playback_provider COMMENT '播放提供商(已废弃)';
ALTER TABLE playback_request COMMENT '播放请求(已废弃)';
ALTER TABLE playback_result COMMENT '播放结果(已废弃)';
ALTER TABLE playback_attempt COMMENT '播放尝试(已废弃)';
ALTER TABLE playback_route COMMENT '播放路由(已废弃)';
ALTER TABLE playback_route_group COMMENT '播放路由组(已废弃)';
ALTER TABLE playback_rule COMMENT '播放规则(已废弃)';
ALTER TABLE route_health COMMENT '路由健康状态(已废弃)';
ALTER TABLE route_metric_minute COMMENT '路由每分钟指标(已废弃)';

-- ====== 风控 ======
ALTER TABLE risk_blacklist COMMENT '风控黑名单';
ALTER TABLE risk_blacklist MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE risk_blacklist MODIFY COLUMN blacklist_type VARCHAR(32) NOT NULL COMMENT '黑名单类型: IP/DEVICE/USER';
ALTER TABLE risk_blacklist MODIFY COLUMN target_value VARCHAR(256) NOT NULL COMMENT '黑名单目标值';
ALTER TABLE risk_blacklist MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE/INACTIVE';
ALTER TABLE risk_blacklist MODIFY COLUMN reason VARCHAR(512) NULL COMMENT '加黑原因';
ALTER TABLE risk_blacklist MODIFY COLUMN start_time DATETIME NULL COMMENT '生效时间';
ALTER TABLE risk_blacklist MODIFY COLUMN end_time DATETIME NULL COMMENT '失效时间(空=永久)';
ALTER TABLE risk_blacklist MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE risk_blacklist MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE risk_event COMMENT '风控事件';
ALTER TABLE risk_event MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE risk_event MODIFY COLUMN risk_event_type VARCHAR(64) NOT NULL COMMENT '事件类型';
ALTER TABLE risk_event MODIFY COLUMN user_id BIGINT NULL COMMENT '用户ID';
ALTER TABLE risk_event MODIFY COLUMN device_id VARCHAR(128) NULL COMMENT '设备ID';
ALTER TABLE risk_event MODIFY COLUMN ip_address VARCHAR(64) NULL COMMENT 'IP地址';
ALTER TABLE risk_event MODIFY COLUMN risk_level VARCHAR(32) NOT NULL COMMENT '风险等级: LOW/MEDIUM/HIGH/CRITICAL';
ALTER TABLE risk_event MODIFY COLUMN action VARCHAR(32) NOT NULL COMMENT '处理动作: LOG/BLOCK/CHALLENGE';
ALTER TABLE risk_event MODIFY COLUMN evidence JSON NULL COMMENT '证据数据';
ALTER TABLE risk_event MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE risk_rule COMMENT '风控规则';
ALTER TABLE risk_rule MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE risk_rule MODIFY COLUMN rule_code VARCHAR(64) NOT NULL COMMENT '规则编码';
ALTER TABLE risk_rule MODIFY COLUMN event_type VARCHAR(64) NOT NULL COMMENT '关联事件类型';
ALTER TABLE risk_rule MODIFY COLUMN threshold INT NOT NULL COMMENT '触发阈值';
ALTER TABLE risk_rule MODIFY COLUMN window_seconds INT NOT NULL COMMENT '时间窗口(秒)';
ALTER TABLE risk_rule MODIFY COLUMN action VARCHAR(32) NOT NULL COMMENT '动作: LOG/BLOCK/CHALLENGE';
ALTER TABLE risk_rule MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用';
ALTER TABLE risk_rule MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE risk_rule MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- ====== 用户 ======
ALTER TABLE user_account COMMENT '用户账号';
ALTER TABLE user_account MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE user_account MODIFY COLUMN user_no VARCHAR(32) NOT NULL COMMENT '用户编号(系统内部)';
ALTER TABLE user_account MODIFY COLUMN mobile VARCHAR(20) NULL COMMENT '手机号';
ALTER TABLE user_account MODIFY COLUMN nickname VARCHAR(64) NULL COMMENT '昵称';
ALTER TABLE user_account MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE/DISABLED/DELETED';
ALTER TABLE user_account MODIFY COLUMN risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW' COMMENT '风险等级: LOW/MEDIUM/HIGH';
ALTER TABLE user_account MODIFY COLUMN password VARCHAR(100) NULL COMMENT '登录密码(BCrypt哈希)';
ALTER TABLE user_account MODIFY COLUMN entitlement_code VARCHAR(64) NULL COMMENT '权益码(注册时写入)';
ALTER TABLE user_account MODIFY COLUMN last_login_at DATETIME NULL COMMENT '最后登录时间';
ALTER TABLE user_account MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE user_account MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE user_account MODIFY COLUMN deleted_at DATETIME NULL COMMENT '软删除时间';

ALTER TABLE user_device COMMENT '用户设备';
ALTER TABLE user_device MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE user_device MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID';
ALTER TABLE user_device MODIFY COLUMN device_public_id VARCHAR(128) NOT NULL COMMENT '设备公开标识';
ALTER TABLE user_device MODIFY COLUMN client_type VARCHAR(32) NOT NULL COMMENT '客户端类型: ANDROID/IOS/WEB';
ALTER TABLE user_device MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态';
ALTER TABLE user_device MODIFY COLUMN app_version VARCHAR(32) NULL COMMENT 'App版本号';
ALTER TABLE user_device MODIFY COLUMN last_active_at DATETIME NULL COMMENT '最后活跃时间';
ALTER TABLE user_device MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE user_device MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE user_entitlement COMMENT '用户权益关联';
ALTER TABLE user_entitlement MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE user_entitlement MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID';
ALTER TABLE user_entitlement MODIFY COLUMN entitlement_id BIGINT NOT NULL COMMENT '权益ID';
ALTER TABLE user_entitlement MODIFY COLUMN entitlement_code VARCHAR(16) NULL COMMENT '权益编码';
ALTER TABLE user_entitlement MODIFY COLUMN obtained_at DATETIME NULL COMMENT '获得时间';
ALTER TABLE user_entitlement MODIFY COLUMN expire_time DATETIME NULL COMMENT '到期时间(空=永久)';
ALTER TABLE user_entitlement MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE/EXPIRED/REVOKED';
ALTER TABLE user_entitlement MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE user_entitlement MODIFY COLUMN updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE user_login_log COMMENT '用户登录日志';
ALTER TABLE user_login_log MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE user_login_log MODIFY COLUMN user_id BIGINT NULL COMMENT '用户ID';
ALTER TABLE user_login_log MODIFY COLUMN device_public_id VARCHAR(128) NULL COMMENT '设备标识';
ALTER TABLE user_login_log MODIFY COLUMN ip_address VARCHAR(64) NULL COMMENT 'IP地址';
ALTER TABLE user_login_log MODIFY COLUMN user_agent VARCHAR(512) NULL COMMENT 'User-Agent';
ALTER TABLE user_login_log MODIFY COLUMN login_result VARCHAR(32) NOT NULL COMMENT '登录结果: SUCCESS/FAILURE';
ALTER TABLE user_login_log MODIFY COLUMN failure_reason VARCHAR(256) NULL COMMENT '失败原因';
ALTER TABLE user_login_log MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

-- ====== 平台管理 ======
ALTER TABLE video_platform COMMENT '视频平台';
ALTER TABLE video_platform MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE video_platform MODIFY COLUMN platform_code VARCHAR(64) NOT NULL COMMENT '平台编码: cctv/fanqie/...';
ALTER TABLE video_platform MODIFY COLUMN platform_name VARCHAR(128) NOT NULL COMMENT '平台名称';
ALTER TABLE video_platform MODIFY COLUMN home_url VARCHAR(512) NOT NULL COMMENT '首页URL';
ALTER TABLE video_platform MODIFY COLUMN description VARCHAR(512) NULL COMMENT '描述';
ALTER TABLE video_platform MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用';
ALTER TABLE video_platform MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE/INACTIVE';
ALTER TABLE video_platform MODIFY COLUMN platform_type VARCHAR(32) NULL DEFAULT 'video' COMMENT '平台类型: video/music/tv/drama';
ALTER TABLE video_platform MODIFY COLUMN logo_url VARCHAR(512) NULL COMMENT 'Logo图标链接';
ALTER TABLE video_platform MODIFY COLUMN minimum_android_version VARCHAR(32) NULL COMMENT '最低Android版本';
ALTER TABLE video_platform MODIFY COLUMN minimum_ios_version VARCHAR(32) NULL COMMENT '最低iOS版本';
ALTER TABLE video_platform MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE video_platform MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE video_platform_domain COMMENT '平台域名';
ALTER TABLE video_platform_domain MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE video_platform_domain MODIFY COLUMN platform_id BIGINT NOT NULL COMMENT '平台ID';
ALTER TABLE video_platform_domain MODIFY COLUMN scheme VARCHAR(16) NOT NULL DEFAULT 'https' COMMENT '协议: http/https';
ALTER TABLE video_platform_domain MODIFY COLUMN host VARCHAR(256) NOT NULL COMMENT '域名';
ALTER TABLE video_platform_domain MODIFY COLUMN include_subdomains TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否包含子域名';
ALTER TABLE video_platform_domain MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用';
ALTER TABLE video_platform_domain MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE video_url_rule COMMENT '视频URL规则';
ALTER TABLE video_url_rule MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE video_url_rule MODIFY COLUMN platform_id BIGINT NOT NULL COMMENT '平台ID';
ALTER TABLE video_url_rule MODIFY COLUMN rule_type VARCHAR(32) NOT NULL COMMENT '规则类型';
ALTER TABLE video_url_rule MODIFY COLUMN pattern VARCHAR(1024) NOT NULL COMMENT 'URL匹配模式';
ALTER TABLE video_url_rule MODIFY COLUMN priority INT NOT NULL DEFAULT 0 COMMENT '优先级(数值越大越高)';
ALTER TABLE video_url_rule MODIFY COLUMN extract_config JSON NULL COMMENT '提取配置';
ALTER TABLE video_url_rule MODIFY COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用';
ALTER TABLE video_url_rule MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE video_url_rule MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
